cages = Cage.create([{ capacity: 10 }, { capacity: 20 }, { capacity: 1 }])

Species.create(name: 'Tyrannosaurus', diet: 'carnivore')
Species.create(name: 'Velociraptor', diet: 'carnivore')
Species.create(name: 'Spinosaurus', diet: 'carnivore')
Species.create(name: 'Megalosaurus', diet: 'carnivore')
Species.create(name: 'Brachiosaurus', diet: 'herbivore')
Species.create(name: 'Stegosaurus', diet: 'herbivore')
Species.create(name: 'Ankylosaurus', diet: 'herbivore')
Species.create(name: 'Triceratops', diet: 'herbivore')
